// Generated by CoffeeScript 2.6.0
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    return $stateProvider.state('agency_client-management-list', {
      url: '/agency/client-management',
      template: require("./client-management-list.html").default,
      controller: 'agencyClientManagementListCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Client Management',
		auth: ['agency:agency', 'agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
  });

}).call(this);
