// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    return $stateProvider.state('agency_solicitors', {
      url: '/agency/solicitors',
      template: require("./solicitors.html").default,
      controller: 'agencySolicitorsCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Solicitors',
		auth: ['agency:agency', 'agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
  });

}).call(this);
