// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsIssueDeleteCtrl', function($scope, data, $http, ndxModalInstance) {
    $scope.data = data;
    $scope.submit = function() {
      return ndxModalInstance.close('thingy');
    };
    return $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

}).call(this);
