// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').config(function($stateProvider) {
    return $stateProvider.state('lettings_dashboardItem', {
      url: '/lettings/dashboard-item/:id/:type',
      template: require("./dashboard-item.html").default,
      controller: 'lettingsDashboardItemCtrl',
      data: {
        title: 'Vitalspace Lettings - Dashboard Item',
		auth: ['lettings:admin', 'lettings:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['lettings:admin', 'lettings:superadmin']);
        }
      }
    });
  });

}).call(this);
