// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').controller('lettingsDashboardItemCtrl', function($scope, $stateParams, $window, alert) {
    $scope.type = $stateParams.type;
    $scope.dashboardItem = $scope.single('lettings:dashboard', $stateParams.id, function(item) {
      if (item) {
        return $scope.dashboardItem.locked = true;
      }
    });
    $scope.progressions = $scope.list('lettings:progressions', {
      sort: 'i'
    });
    $scope.getMilestones = function() {
      var branch, i, j, len, len1, output, progression, ref, ref1;
      if ($scope.progressions && $scope.progressions.items && $scope.dashboardItem && $scope.dashboardItem.item) {
        ref = $scope.progressions.items;
        for (i = 0, len = ref.length; i < len; i++) {
          progression = ref[i];
          if (progression._id === $scope.dashboardItem.item.progression) {
            output = [];
            ref1 = progression.milestones;
            for (j = 0, len1 = ref1.length; j < len1; j++) {
              branch = ref1[j];
              output.push(branch[0]);
            }
            return output;
          }
        }
      }
    };
    $scope.save = function() {
      $scope.dashboardItem.item.type = $scope.type;
      $scope.dashboardItem.save();
      alert.log('Dashboard item saved');
      return $window.history.go(-1);
    };
    return $scope.cancel = function() {
      return $window.history.go(-1);
    };
  });

}).call(this);
