// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsWorksOrdersCtrl', function($scope, Sorter, DbItem) {
    $scope.dbItem = DbItem;
    $scope.page = 1;
    $scope.limit = 15;
    $scope.mysearch = {
      $like: ''
    };
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.issues = $scope.list('maintenance_leads:issues', {
      page: 1,
      pageSize: 10,
      sort: 'date',
      sortDir: 'DESC',
      where: {
        statusName: 'Booked',
        search: $scope.mysearch,
        status: {
          booked: true,
          completed: false,
          invoiced: false
        }
      }
    });
    $scope.sort = Sorter.create($scope.issues.args);
    
    $scope.showLightbox = function(media) {
      return $scope.modal({
        template: require('../../modals/lightbox/lightbox.html').default,
        controller: 'maintenance_leadsLightboxCtrl',
        size: 'large',
        data: media
      }).then(function() {});
    };
    
    $scope.openAddIssueModal = function() {
      return $scope.modal({
        template: require('../../modals/add-issue/add-issue.html').default,
        controller: 'maintenance_leadsAddIssueModalCtrl',
        size: 'large',
        data: {}
      }).then(function(newIssue) {
        if (newIssue) {
          $scope.issues.refresh();
        }
      });
    };
    
    return $scope.openAddWorksOrderModal = function() {
      return $scope.modal({
        template: require('../../modals/add-works-order/add-works-order.html').default,
        controller: 'maintenance_leadsAddWorksOrderModalCtrl',
        size: 'large',
        data: {}
      }).then(function(newWorksOrder) {
        if (newWorksOrder) {
          // Optionally refresh or show success message
        }
      });
    };
  });

}).call(this);
