// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_worksorders', {
      url: '/maintenance_leads/works-orders',
      template: require("./works-orders.html").default,
      controller: 'maintenance_leadsWorksOrdersCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - Outstanding Works Orders',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin', 'maintenance_leads:agency']
      }
    });
  });

}).call(this);
