// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  var e;

  angular.module('vs-lettings', ['ndx', 'ui.router', 'multi-check', 'ui.gravatar', 'ngFileUpload', 'vs-lettings-inner', 'lettings-date-swiper', 'yaru22.angular-timeago', 'angular-flipclock']).config(function($locationProvider, $urlRouterProvider, gravatarServiceProvider) {
    $urlRouterProvider.otherwise('/');
    $locationProvider.html5Mode(true);
    gravatarServiceProvider.defaults = {
      size: 16,
      "default": 'mm',
      rating: 'pg'
    };
  }).run(function($rootScope, $state, LettingsProgressionPopup, $http, $transitions, ndxModal, env) {
    var root;
    $http.defaults.headers.common.Authorization = `Bearer ${env.PROPERTY_TOKEN}`;
    $rootScope.state = function(route) {
      if ($state && $state.current) {
        if (Object.prototype.toString.call(route) === '[object Array]') {
          return route.indexOf($state.current.name) !== -1;
        } else {
          return route === $state.current.name;
        }
      }
      return false;
    };
    $transitions.onBefore({}, function(trans) {
      if (trans.$from().name) {
        LettingsProgressionPopup.hide();
        return $('body').removeClass(`${trans.$from().name}-page`);
      }
    });
    $transitions.onFinish({}, function(trans) {
      if (trans.$to().name) {
        return $('body').addClass(`${trans.$to().name}-page`);
      }
    });
    $rootScope.makeDownloadUrl = function(document) {
      if (document) {
        return $http.sites["lettings"].url + '/api/download/' + btoa(JSON.stringify({
          path: document.path,
          filename: document.originalFilename
        }));
      }
    };
    root = Object.getPrototypeOf($rootScope);
    root.generateId = function(len) {
      var i, letters, output;
      letters = "abcdefghijklmnopqrstuvwxyz0123456789";
      output = '';
      i = 0;
      while (i++ < len) {
        output += letters[Math.floor(Math.random() * letters.length)];
      }
      return output;
    };
    return root.hidePopup = function(ev) {
      return LettingsProgressionPopup.hide();
    };
  });

  try {
    angular.module('ndx');
  } catch (error) {
    e = error;
    angular.module('ndx', []); //ndx module stub
  }

  angular.module('vs-lettings-inner', []);

}).call(this);
