// Generated by CoffeeScript 2.6.0
(function() {
  'use strict';
  angular.module('vs-agency').filter('daysSince', function() {
    return function(date) {
      var noDays, oldDate;
      if (date) {
        oldDate = new Date(date);
        noDays = Math.floor((new Date().valueOf() - oldDate.valueOf()) / (24 * 60 * 60 * 1000));
        return `${noDays} ${noDays === 1 ? 'day' : 'days'}`;
      }
    };
  });

}).call(this);
