// Generated by CoffeeScript 2.6.0
(function() {
  'use strict';
  angular.module('vs-agency').filter('getFees', function() {
    return function(property) {
      if (!property) {
        return;
      }
      if (!property.Fees[0]) {
        return;
      }
      if (property.Fees[0].FeeValueType.DisplayName === 'Percentage') {
        return +property.Price.PriceValue * (+property.Fees[0].DefaultValue / 100);
      } else {
        return property.Fees[0].DefaultValue;
      }
    };
  });

}).call(this);
