// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').directive('chainItem', function() {
    return {
      restrict: 'EA',
      template: require("./chain-item.html").default,
      replace: true
    };
  });

}).call(this);
