// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings').controller('lettingsRequestEmailCtrl', function($scope, $http, data, ndxModalInstance) {
    $scope.forms = {};
    $scope.data = {
      type: data.type,
      property: data.property,
      toName: '',
      toMail: '',
      refName: '',
      refMail: ''
    };
    $scope.submit = function() {
      $scope.submitted = true;
      if ($scope.forms.myform.$valid) {
        $http.post($http.sites["lettings"].url + '/api/properties/send-request-email', $scope.data);
        return ndxModalInstance.dismiss();
      }
    };
    return $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

}).call(this);
