// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    return $stateProvider.state('agency_dashboardItem', {
      url: '/agency/dashboard-item/:id/:type',
      template: require("./dashboard-item.html").default,
      controller: 'agencyDashboardItemCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Dashboard Item',
		auth: ['agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['agency:admin', 'agency:superadmin']);
        }
      }
    });
  });

}).call(this);
