// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_issues', {
      url: '/maintenance_leads/issues',
      template: require("./issues.html").default,
      controller: 'maintenance_leadsIssuesCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - Issues',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin', 'maintenance_leads:agency']
      }
    });
  });

}).call(this);
