// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsAddIssueModalCtrl', function($scope, $http, ndxModalInstance, data) {
    $scope.data = data || {};
    $scope.submitted = false;
    $scope.forms = {};
    
    // Initialize issue object
    if ($scope.data.issue) {
      // Editing existing issue
      $scope.issue = $scope.data.issue;
    } else {
      // Creating new issue
      $scope.issue = $scope.single('maintenance_leads:issues', {}, function(issue) {
        issue.item = {
          source: '',
          date: new Date()
        };
      });
    }
    
    // Load sources
    $scope.sources = [
      { _id: 'email', name: 'Email' },
      { _id: 'telephone', name: 'Telephone' },
      { _id: 'walkin', name: 'Walk In' },
      { _id: 'fixflo', name: 'FixFlo' }
    ];
    
    // Load landlords
    $scope.landlords = $scope.list('maintenance_leads:landlords', {
      page: 1,
      pageSize: 1000,
      sort: 'name',
      sortDir: 'ASC'
    });
    
    $scope.save = function() {
      $scope.submitted = true;
      
      if (!$scope.forms.myForm || !$scope.forms.myForm.$valid) {
        return;
      }
      
      $scope.issue.save().then(function() {
        ndxModalInstance.close($scope.issue.item);
      }, function(err) {
        console.error('Error saving issue:', err);
        alert('Error saving issue. Please try again.');
      });
    };
    
    $scope.cancel = function() {
      ndxModalInstance.dismiss();
    };
  });

}).call(this);
