// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').directive('mobileMenu', function() {
    return {
      restrict: 'AE',
      template: require("./mobile-menu.html").default,
      replace: true,
      link: function(scope) {}
    };
  });

}).call(this);
