// Generated by CoffeeScript 2.6.0
(function () {
  'use strict';
  angular.module('vs-agency').config(function ($stateProvider) {
    $stateProvider.state('agency_offers-list', {
      url: '/agency/offers',
      template: require("./offers-list.html").default,
      controller: 'agencyOffersListCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Pending Offers',
        auth: ['agency:agency', 'agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function (Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
    $stateProvider.state('agency_offers-list_historic', {
      url: '/agency/offers/historic',
      template: require("./offers-list.html").default,
      controller: 'agencyOffersListCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Pending Offers',
        auth: ['agency:agency', 'agency:admin', 'agency:superadmin'],
        data: {
          isHistoric: true
        }
      },
      resolve: {
        user: function (Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
  });

}).call(this);
