// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').directive('lettingsMilestone', function($rootScope, LettingsProgressionPopup) {
    return {
      restrict: 'AE',
      template: require("./milestone.html").default,
      replace: true,
      scope: {
        milestone: '=data',
        disabled: '@'
      },
      link: function(scope, elem, attrs) {
        // If no icon is set, use slugified title as fallback
        if (!scope.milestone.icon && scope.milestone.title) {
          scope.milestone.icon = scope.milestone.title.toLowerCase()
            .replace(/&/g, 'and')
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-'); 
        }
        
        scope.getClass = function() {
          return {
            completed: scope.milestone.completed,
            progressing: scope.milestone.progressing,
            overdue: scope.milestone.completed ? false : scope.milestone.progressing && new Date().valueOf() > (scope.milestone.userCompletedTime || scope.milestone.estCompletedTime)
          };
        };
        return scope.itemClick = function() {
          var myscope, property;
          if (scope.disabled !== 'true') {
            myscope = scope;
            while (myscope && !(property = myscope.property)) {
              myscope = myscope.$parent;
            }
            return LettingsProgressionPopup.show(elem[0], scope.milestone, property);
          }
        };
      }
    };
  });

  //$rootScope.$emit 'swiper:show'

}).call(this);
