// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').controller('lettingsMarketingCtrl', function($scope, env, $http) {
    $scope.propsOpts = {
      where: {
        RoleStatus: 'InstructionToLet',
        RoleType: 'Letting',
        IncludeStc: true
      },
      transform: {
        items: 'Collection',
        total: 'TotalCount'
      }
    };
    $scope.properties = $scope.list({
      route: `${env.PROPERTY_URL}/search`
    }, $scope.propsOpts);
    return $scope.submit = function() {
      $scope.submitted = true;
      if ($scope.marketingEmail.$valid) {
        return $http.post($http.sites["lettings"].url + '/api/properties/send-marketing-email', {
          marketing: $scope.marketing
        }, $http.sites["lettings"].config).then(function() {
          return $scope.emailSent = true;
        });
      }
    };
  });

}).call(this);
