// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsIssueBookCtrl', function($scope, data, $http, ndxModalInstance) {
    $scope.data = data;
    $scope.forms = {};
    $scope.redirect = null;
    $scope.saveFn = function(cb) {
      ndxModalInstance.close($scope.forms.myForm.jobnumber.$modelValue);
      return cb(false);
    };
    return $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

}).call(this);
