// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').factory('agencyProperty', function() {
    var property;
    property = null;
    return {
      get: function() {
        return property;
      },
      set: function(prop) {
        return property = prop;
      }
    };
  });

}).call(this);
