// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    $stateProvider.state('agency_case', {
      url: '/agency/case/:roleId',
      template: require("./case.html").default,
      controller: 'agencyCaseCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Case',
		auth: ['agency:agency', 'agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
  });

}).call(this);
