// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').config(function($stateProvider) {
    $stateProvider.state('leads_lead-new', {
      url: '/leads/lead',
      template: require("./lead.html").default,
      controller: 'leadsLeadCtrl',
      params: {
        _id: null
      },
      data: {
        title: 'Vitalspace Leads - Lead',
        auth: ['leads:superadmin', 'leads:admin', 'leads:agency']
      }
    });
    $stateProvider.state('leads_lead', {
      url: '/leads/lead/:_id',
      template: require("./lead.html").default,
      controller: 'leadsLeadCtrl',
      data: {
        title: 'Vitalspace Leads - Lead',
        auth: ['leads:superadmin', 'leads:admin', 'leads:agency']
      }
    });
    return $stateProvider.state('leads_leadDeleted', {
      url: '/leads/lead/:_id/all',
      template: require("./lead.html").default,
      controller: 'leadsLeadCtrl',
      params: {
        $or: [
          {deleted: {
            $nn: true
          }},
          {booked: true}
        ]
      },
      data: {
        title: 'Vitalspace Leads - Lead',
        auth: ['leads:superadmin', 'leads:admin']
      }
    });
  });

}).call(this);
