// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').directive('header', function($rootScope) {
    return {
      restrict: 'EA',
      template: require("./header.html").default,
      replace: true,
      link: function(scope, elem, attrs) {
        return scope.toggleMobileMenu = function($event) {
          $rootScope.mobileMenuOut = !$rootScope.mobileMenuOut;
          return $event.stopPropagation();
        };
      }
    };
  });

}).call(this);
