// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_landlord', {
      url: '/maintenance_leads/landlord/:_id',
      template: require("./landlord.html").default,
      controller: 'maintenance_leadslandlordCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - landlord',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin', 'maintenance_leads:agency']
      }
    });
  });

}).call(this);
