// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').controller('lettingsTemplateCtrl', function($scope, $stateParams, $state, $http, env) {
    var cb, fetchDefaultProp;
    $scope.type = $stateParams.type;
    cb = function(template) {
      if (template) {
        return $scope.template.locked = true;
      }
    };
    if ($stateParams.type === 'email') {
      $scope.lang = 'pug';
      $scope.template = $scope.single('lettings:emailtemplates', $stateParams.id, cb);
    } else {
      $scope.lang = 'text';
      $scope.template = $scope.single('lettings:smstemplates', $stateParams.id, cb);
    }
    $scope.save = function() {
      if ($scope.myForm.$valid) {
        $scope.template.save();
        return $state.go('lettings_setup');
      }
    };
    $scope.cancel = function() {
      return $state.go('lettings_setup');
    };
    $scope.defaultData = {
      displayAddress: "26 Chervil Close, Fallowfield, Manchester, M14 7DP",
      text: marked("## Advance Progression Request  \n#### Milestone  \n`Searches Completed`  \n#### Advance to  \n`Wed May 24 2017`  \n#### Requested by  \n`Dawn Wetherill`  \n#### Reason  \nA reason  \n"),
      link: "https://lettings.vitalspace.co.uk/case/10993717",
      applicant: {
        title: "Mr",
        firstName: "Richard",
        lastName: "Antrobus",
        terms: "12",
        movingInDate: "2019-01-15T00:00:00.000Z",
        rent: "1000",
        deposit: "1000"
      },
      marketing: {
        address: "67 Little Bolton Terrace, Salford",
        availableDate: "2019-01-15T00:00:00.000Z",
        tendDate: "2019-01-15T00:00:00.000Z",
        rent: "1000",
        historicRent: "800",
        terms: "12",
        pStatus: "Furnished",
        access: "A load of text about the access details",
        repairs: "A load of text about repairs",
        lfees: "Managed",
        tfamount: "200",
        mamount: "200",
        ma: "5",
        board: "Yes",
        windowcard: "Yes",
        epc: "Yes",
        gas: "Yes",
        cfp: "Yes",
        eicr: "Yes"
      }
    };
    fetchDefaultProp = function() {
      return $http.post(`${env.PROPERTY_URL}/search`, {
        RoleStatus: 'OfferAccepted',
        RoleType: 'Letting',
        IncludeStc: true,
        PageSize: 1
      }, $http.sites["lettings"].config).then(function(response) {
        if (response.data && response.data.Collection && response.data.Collection.length) {
          $scope.defaultData.property = response.data.Collection[0];
	      const availableDate = new Date($scope.defaultData.property.AvailableDate);
	      let availableDateVal = availableDate.valueOf() - (availableDate.getTimezoneOffset() * 60 * 1000);
          return $http.get($http.sites["lettings"].url + `/api/properties/${$scope.defaultData.property.RoleId + '_' + availableDateVal}`, $http.sites["lettings"].config).then(function(response) {
            if (response.data) {
              $scope.defaultData.property.case = response.data;
              return $scope.defaultData.contact = response.data.vendorsContact;
            }
          });
        }
      });
    };
    return fetchDefaultProp();
  });

}).call(this);
