// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').config(function($stateProvider) {
    return $stateProvider.state('leads_setup', {
      url: '/leads/setup',
      template: require("./setup.html").default,
      controller: 'leadsSetupCtrl',
      data: {
        title: 'Vitalspace Leads - Setup',
        auth: ['leads:superadmin', 'leads:admin']
      }
    });
  });

}).call(this);
