// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').config(function($stateProvider) {
    return $stateProvider.state('leads_invited', {
      url: '/leads/invite/:code',
      template: require("./invited.html").default,
      controller: 'leadsInvitedCtrl',
      data: {
        title: 'Vitalspace Leads - Invited'
      }
    });
  });

}).call(this);
