// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('ndx').directive('paging', function() {
    return {
      restrict: 'EA',
      template: require("./paging.html").default,
      replace: true,
      scope: {
        total: '=',
        opts: '='
      },
      link: function(scope, elem, attrs) {
        return true;
      }
    };
  });

}).call(this);
