// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('ndx').directive('popout', function() {
    return {
      restrict: 'A',
      link: function(scope, elem, attrs) {
        return $(elem[0]).addClass('has-popout').on('click', function() {
          var elm;
          elm = $(this).parent().find('.popout');
          if (elm.hasClass('out')) {
            return elm.removeClass('out');
          } else {
            return elm.addClass('out');
          }
        });
      }
    };
  });

}).call(this);
