// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').controller('agencyInvitedCtrl', function($scope, $state, $http) {
    var code, codeBits, e;
    code = window.location.search.replace(/^\?/, '');
    codeBits = unescape(code).split(/  /);
    if (codeBits.length === 2) {
      code = codeBits[0];
      try {
        $scope.newUser = JSON.parse(atob(codeBits[1]));
      } catch (error) {
        e = error;
        false;
      }
    }
    return $scope.acceptInvite = function() {
      if ($scope.repeatPassword === $scope.newUser.local.password) {
        return $http.post('/invite/accept', {
          code: decodeURIComponent(code),
          user: $scope.newUser
        }, $http.sites["agency"].config).then(function(response) {
          if (response.data === 'OK') {
            return $state.go('dashboard');
          }
        }, function(err) {
          return false;
        });
      } else {
        return $scope.error = 'Passwords must match';
      }
    };
  });

}).call(this);
