// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('ndx').directive('templateRender', function($timeout) {
    return {
      restrict: 'AE',
      replace: true,
      require: 'ngModel',
      template: '<div class="template-render"></div>',
      scope: {
        data: '=',
        ngModel: '='
      },
      link: function(scope, elem, attrs, ngModel) {
        var fillTemplate, render;
        fillTemplate = function(template, data) {
          return template.replace(/\{\{(.+?)\}\}/g, function(all, match) {
            var evalInContext;
            evalInContext = function(str, context) {
              return (new Function(`with(this) {return ${str}}`)).call(context);
            };
            return evalInContext(match, data);
          });
        };
        render = function() {
          var e;
          try {
            return elem[0].innerText = fillTemplate(scope.ngModel, scope.data);
          } catch (error) {
            e = error;
            return false;
          }
        };
        ngModel.$formatters.unshift(function(val) {
          render();
          return val;
        });
        return scope.$watch('data', function(n, o) {
          if (n) {
            return $timeout(render, 500);
          }
        });
      }
    };
  });

}).call(this);
