// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    return $stateProvider.state('agency_dashboard', {
      url: '/agency',
      template: require("./dashboard.html").default,
      controller: 'agencyDashboardCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Dashboard'
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise();
        }
      }
    });
  });

}).call(this);
