// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').controller('agencyDashboardCtrl', function($scope, $filter, env, $http, alert) {
    var bmonth, i, month, monthNames, now;
    $scope.consultantTotals = {};
    $scope.unknownConsultant = {};
    $scope.unknownSolicitor = {};
    $scope.unknownConsultantCount = () => Object.keys($scope.unknownConsultant).length;
    $scope.unknownSolicitorCount = () => Object.keys($scope.unknownSolicitor).length;
    $scope.propsOpts = {
      where: {
        delisted: null
      }
    };
    // consultant
    $scope.consultants = $scope.list('main:users', null, (users) => {
      users.items = users.items.filter(user => {
        const siteRole = user.siteRoles && user.siteRoles.find(role => role.siteId==='agency' && user.displayName!=='lettings');
        if(user.email==='richard@vitalspace.co.uk') return true;
        if(siteRole) {
          return siteRole.role==='agency' || siteRole.role==='admin';
        }
        return false;
      }).sort((a, b) => a.displayName > b.displayName ? 1 : -1);
    });
    // propertyadmin
    $scope.propertyadmin = $scope.list('main:propertyadmin');
    //properties
    let historic = null;
    $http.get('/public/data/conveyancing-historic.json').then(res => {
      historic = res.data;
    });
    $scope.properties = $scope.list('agency:properties', {
      where: {modifiedAt:{$gt:new Date('2022-12-20').valueOf()}},
      transformer: 'dashboard/properties'
    }, function(properties) {
      var completeBeforeDelisted, i, milestone, progression, property, results;
      i = properties.items.length;
      results = [];
      while (i-- > 0) {
        property = properties.items[i];
        if (property.override && property.override.deleted) {
          properties.items.splice(i, 1);
          continue;
        }
        completeBeforeDelisted = false;
        if (property.progressions && property.progressions.length) {
          progression = property.progressions[0];
          milestone = progression.milestones[progression.milestones.length - 1];
          completeBeforeDelisted = !milestone[0].completed && property.delisted || !property.delisted;
          const stale = new Date(property.role.CreatedDate) < (new Date() - (365 * 24 * 60 * 60 * 1000));
          if(!milestone[0].completed && !stale) {
            if(!property.consultant) $scope.unknownConsultant[property._id] = property;
            if(!property.purchasersSolicitor || !Object.keys(property.purchasersSolicitor).length) $scope.unknownSolicitor[property._id] = property;
            if(!property.vendorsSolicitor || !Object.keys(property.vendorsSolicitor).length) $scope.unknownSolicitor[property._id] = property;
          }
        }
        property.completeBeforeDelisted = completeBeforeDelisted;
      }
    });
    $scope.dashboard = $scope.list('agency:dashboard', {
      sort: 'i'
    }, (dashboard) => {
      $scope.dashboardExchangeItem = dashboard.items.find(function(item) {
        return item.name === 'Exchanges';
      });
    });
    $scope.progressions = $scope.list('agency:progressions');

    $scope.clientmanagement = $scope.list('agency:clientmanagement', {
      where: {
        active: true
      }
    }, function(properties) {
      properties.items.forEach(property => {
        property.roleId = property.RoleId.toString();
        property.type = 'clientmanagment';
      })
    });

    // #region refactor
    $scope.count = function(di, list, pipeline) {
      var output = [];
      var count = 0;
      var minIndex = 0;
      var maxIndex = 100;
      var i, j, k, l, m, n, o, p;
      var progression, property, branch, milestone;

      if (historic && historic[di._id]) {
        return list ? historic[di._id].list : historic[di._id].count;
      }

      if (!($scope.properties && $scope.properties.items && $scope.progressions && $scope.progressions.items)) {
        return list ? [] : 0;
      }

      for (i = 0; i < $scope.progressions.items.length; i++) {
        progression = $scope.progressions.items[i];
        if (progression._id === di.progression && progression.milestones) {
          for (j = 0; j < progression.milestones.length; j++) {
            branch = progression.milestones[j];
            if (!branch) continue;
            for (k = 0; k < branch.length; k++) {
              milestone = branch[k];
              if (milestone._id === di.minms) minIndex = j;
              if (milestone._id === di.maxms) maxIndex = j;
            }
          }
        }
      }

      for (l = 0; l < $scope.properties.items.length; l++) {
        property = $scope.properties.items[l];
        if (!property || (pipeline && pipeline !== property.pipeline) || (!pipeline && property.pipeline)) continue;
        if (property.override && property.override.deleted) continue;

        if (property.milestoneIndex && typeof property.milestoneIndex[di.progression] !== 'undefined') {
          var index = property.milestoneIndex[di.progression];
          if (minIndex <= index && index <= maxIndex) {
            var propertyGood = true;

            if (di.min && di.max) {
              propertyGood = false;
              if (property.progressions) {
                for (m = 0; m < property.progressions.length; m++) {
                  progression = property.progressions[m];
                  if (progression._id === di.progression && progression.milestones) {
                    for (n = 0; n < progression.milestones.length; n++) {
                      branch = progression.milestones[n];
                      for (o = 0; o < branch.length; o++) {
                        milestone = branch[o];
                        if (milestone._id === di.minms || milestone._id === di.maxms) {
                          if (milestone.estCompletedTime >= di.min && milestone.estCompletedTime <= di.max) {
                            propertyGood = true;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }

            if (propertyGood) {
              if (list) {
                output.push(property);
              }
              count++;
            }
          }
        }
      }

      return list ? output : count;
    };

    // #endregion

    $scope.total = function(items, pipeline) {
      var item, j, len, total;
      total = 0;
      if (items) {
        for (j = 0, len = items.length; j < len; j++) {
          item = items[j];
          total += $scope.count(item, null, pipeline);
        }
      }
      return total;
    };
    $scope.income = function(di, month, list, pipeline) {
      if (di.sumtype === 'Count') {
        $scope.consultantTotals = {};
      }

      var count = 0;
      var output = [];
      var i, j, k, l, m;
      var property, progression, branch, milestone;
      var value;

      if (!($scope.properties && $scope.properties.items)) {
        return list ? [] : (di.sumtype === 'Income' ? $filter('currency')(0, '£', 2) : 0);
      }

      for (i = 0; i < $scope.properties.items.length; i++) {
        property = $scope.properties.items[i];

        if (!property) continue;
        if ((pipeline && pipeline !== property.pipeline) || (!pipeline && property.pipeline)) continue;
        if (property.override && property.override.deleted) continue;
        if (!property.progressions || !property.completeBeforeDelisted) continue;

        for (j = 0; j < property.progressions.length; j++) {
          progression = property.progressions[j];

          if (progression._id !== di.progression || !progression.milestones) continue;

          for (k = 0; k < progression.milestones.length; k++) {
            branch = progression.milestones[k];
            if (!branch) continue;

            for (l = 0; l < branch.length; l++) {
              milestone = branch[l];
              if (milestone._id !== di.minms) continue;

              if (milestone.estCompletedTime >= month.start && milestone.estCompletedTime <= month.end) {
                value = 0;

                if (di.status === 'Due' && !milestone.completed) {
                  value += property.role && property.role.Commission || 0;
                }

                if (di.status === 'Completed' && milestone.completed) {
                  value += property.role && property.role.Commission || 0;
                }

                if (di.status === 'Started' && milestone.started && !milestone.completed) {
                  value += property.role && property.role.Commission || 0;
                }

                // Increment count
                if (di.sumtype === 'Income') {
                  count += value;
                } else if (value) {
                  count++;
                }

                // Push to output if listing
                if (value && list) {
                  output.push(property);
                }

                break; // only match one milestone per property
              }
            }
          }

          break; // only match one progression per property
        }
      }

      if (list) {
        return output;
      } else if (di.sumtype === 'Income') {
        return $filter('currency')(count, '£', 2);
      } else {
        return count;
      }
    };
    $scope.sum = function(values) {
      return Object.values(values).reduce((r, v) => r + v, 0);
    }
    const diff = [29539304, 29473680, 28993902, 29489529, 28506655, 29530602];
    $scope.consultantPipeline = function() {
      var result = {};
      if (!($scope.consultants && $scope.consultants.items && $scope.properties && $scope.properties.items)) {
        return result;
      }

      for (var i = 0; i < $scope.consultants.items.length; i++) {
        var consultant = $scope.consultants.items[i];
        result[consultant._id] = 0;
      }
      const props = [];
      for (var j = 0; j < $scope.properties.items.length; j++) {
        var property = $scope.properties.items[j];
        if(diff.includes(+property.roleId)) props.push(property);
        if (!property || property.override && property.override.deleted) continue;
        if (!property.role) continue;
        if (property.role.RoleStatus.SystemName !== 'OfferAccepted') continue;
        if (Object.values(property.milestoneIndex)[0]===10) continue;
        var cid = property.consultant;
        if (result.hasOwnProperty(cid)) {
          //if(!props.includes(property.roleId)) props.push(+property.roleId);
          result[cid]++;
        }
      }
      return result;
    };
    $scope.consultantExchanges =  function(di, month) {
      var result = {};
      if (!($scope.consultants && $scope.consultants.items)) return result;

      // Init result map
      for (var i = 0; i < $scope.consultants.items.length; i++) {
        result[$scope.consultants.items[i]._id] = 0;
      }

      var properties = $scope.income(di, month, true); // list=true

      for (var j = 0; j < properties.length; j++) {
        var property = properties[j];
        if (!property || property.override && property.override.deleted) continue;
        if (!property.role) continue;
        //if (property.role.RoleStatus !== 'OfferAccepted' || property.role.RoleType !== 'Selling') continue;
        var cid = property.consultant;
        if (result.hasOwnProperty(cid)) {
          result[cid]++;
        }
      }

      return result;
    };
    $scope.showConsultantExchangesModal = function(di, month, consultantId, consultantName) {
      if (!($scope.properties && $scope.properties.items)) {
        return;
      }

      var properties = $scope.income(di, month, true);
      const list = [];

      for (var j = 0; j < properties.length; j++) {
        var property = properties[j];
        if (!property || property.override && property.override.deleted) continue;
        if (!property.role) continue;
        
        // Filter by consultant if provided
        if (consultantId && property.consultant !== consultantId) continue;
        
        list.push(property);
      }
      
      if (list.length) {
        return $scope.modal({
          template: require('../../modals/dashboard-income/dashboard-income.html').default,
          controller: 'agencyDashboardIncomeCtrl',
          data: {
            di: {
              name: consultantName ? consultantName + ' Exchanges - ' + month.name : di.name,
              sumtype: 'Income'
            },
            month: month,
            list: list
          }
        }).then(function() {
          return true;
        }, function() {
          return false;
        });
      } else {
        alert.log('No exchanges to show');
      }
    };
    $scope.showConsultantPipelineModal = function(consultantId, consultantName) {
      if (!($scope.properties && $scope.properties.items)) {
        return;
      }

      const list = [];
      for (var j = 0; j < $scope.properties.items.length; j++) {
        var property = $scope.properties.items[j];
        if (!property || property.override && property.override.deleted) continue;
        if (!property.role) continue;
        if (property.role.RoleStatus.SystemName !== 'OfferAccepted') continue;
        if (Object.values(property.milestoneIndex)[0]===10) continue;
        
        // Filter by consultant if provided, otherwise show all
        if (consultantId && property.consultant !== consultantId) continue;
        
        list.push(property);
      }
      
      if (list.length) {
        return $scope.modal({
          template: require('../../modals/dashboard-income/dashboard-income.html').default,
          controller: 'agencyDashboardIncomeCtrl',
          data: {
            di: {
              name: consultantName ? consultantName + ' Pipeline' : 'All Pipeline Properties'
            },
            month: '',
            list: list
          }
        }).then(function() {
          return true;
        }, function() {
          return false;
        });
      } else {
        alert.log('No pipeline properties to show');
      }
    };
    $scope.consultantInstructedBy = function() {
      var result = {};
      if (!($scope.consultants && $scope.consultants.items && $scope.properties && $scope.properties.items && $scope.propertyadmin && $scope.propertyadmin.items)) {
        return result;
      }

      for (var i = 0; i < $scope.consultants.items.length; i++) {
        var consultant = $scope.consultants.items[i];
        result[consultant._id] = 0;
      }
      const props = [];
      const allProperties = [...$scope.properties.items, ...$scope.clientmanagement.items];
      for (var i = 0; i < $scope.propertyadmin.items.length; i++) {
        const propertyadminitem = $scope.propertyadmin.items[i];
        // Check if instructionToMarket and instructedBy exist
        if (!propertyadminitem.RoleId || !propertyadminitem.instructionToMarket || !propertyadminitem.instructionToMarket.instructedBy) continue;
        const property = allProperties.find(property => property.roleId===propertyadminitem.RoleId.toString());
        if (!property || property.override && property.override.deleted) continue;
        if(!property.type === 'clientmanagement') {
          if (!property.role) continue;
          if (property.role.RoleStatus.SystemName !== 'OfferAccepted') continue;
          if (Object.values(property.milestoneIndex)[0]===10) continue;
        }
        property.instructedBy = propertyadminitem.instructionToMarket.instructedBy;
        if (result.hasOwnProperty(propertyadminitem.instructionToMarket.instructedBy)) {
          const cid = propertyadminitem.instructionToMarket.instructedBy;
          if(result.hasOwnProperty(cid)) {
            result[cid]++;
          }
          else {
            console.log('missed cid', cid);
          }
        }
      }
      return result;
    }
    $scope.showInstructedByPipelineModal = function(consultantId, consultantName) {
      if (!($scope.properties && $scope.properties.items && $scope.propertyadmin && $scope.propertyadmin.items)) {
        return;
      }

      const allProperties = [...$scope.properties.items, ...$scope.clientmanagement.items];
      const list = [];
      
      for (var i = 0; i < $scope.propertyadmin.items.length; i++) {
        const propertyadminitem = $scope.propertyadmin.items[i];
        if (!propertyadminitem.RoleId || !propertyadminitem.instructionToMarket || !propertyadminitem.instructionToMarket.instructedBy) continue;
        
        // Filter by consultant if provided, otherwise show all
        if (consultantId && propertyadminitem.instructionToMarket.instructedBy !== consultantId) continue;
        
        const property = allProperties.find(property => property.roleId===propertyadminitem.RoleId.toString());
        if (!property || property.override && property.override.deleted) continue;
        if(!property.type === 'clientmanagement') {
          if (!property.role) continue;
          if (property.role.RoleStatus.SystemName !== 'OfferAccepted') continue;
          if (Object.values(property.milestoneIndex)[0]===10) continue;
        }
        list.push(property);
      }
      
      if (list.length) {
        return $scope.modal({
          template: require('../../modals/dashboard-income/dashboard-income.html').default,
          controller: 'agencyDashboardIncomeCtrl',
          data: {
            di: {
              name: consultantName ? 'Instructed by ' + consultantName : 'All Instructed Properties'
            },
            month: '',
            list: list
          }
        }).then(function() {
          return true;
        }, function() {
          return false;
        });
      } else {
        alert.log('No instructed properties to show');
      }
    }
    $scope.showInstructedByModal = function(di, month) {
      if (!($scope.properties && $scope.properties.items)) {
        return;
      }

      const list = $scope.income(di, month, true);
      
      if (list.length) {
        // Always set sumtype to 'Income' for commission display
        const diData = Object.assign({}, di, {sumtype: 'Income'});
        
        return $scope.modal({
          template: require('../../modals/instructed-by/instructed-by.html').default,
          controller: 'agencyInstructedByCtrl',
          data: {
            di: diData,
            month: month,
            list: list
          }
        }).then(function() {
          return true;
        }, function() {
          return false;
        });
      }
      else {
        alert.log('No instructions to show for ' + month.name);
      }
    }
    $scope.showInfo = function(type, di, month, pipeline) {
      var list;
      list = null;
      if (type === 'count') {
        list = $scope.count(di, true, pipeline);
      } else {
        list = $scope.income(di, month, true, pipeline);
      }
      if (list.length) {
        return $scope.modal({
          template: require('../../modals/dashboard-income/dashboard-income.html').default,
          controller: 'agencyDashboardIncomeCtrl',
          data: {
            di: di,
            month: month,
            list: list
          }
        }).then(function() {
          return true;
        }, function() {
          return false;
        });
      }
    };
    $scope.showUnknownInfo = (type) => {
      let list = Object.values($scope['unknown' + type]);
      if(list && list.length) {
        $scope.modal({
          template: require('../../modals/dashboard-income/dashboard-income.html').default,
          controller: 'agencyDashboardIncomeCtrl',
          data: {
            di: {
              name: 'Unknown ' + type
            },
            month: '',
            list: list
          }
        }).then(function() {
          return true;
        }, function() {
          return false;
        });
      }
    }
    monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    $scope.months = [];
    now = new Date();
    bmonth = new Date(now.getFullYear(), now.getMonth() - 1);
    $scope.allmonths = {
      start: bmonth.valueOf(),
      end: 0
    };
    $scope.alltime = {
      start: 0,
      end: now.valueOf() + (5 * 365 * 24 * 60 * 60 * 1000)
    };
    i = 0;
    while (i++ < 6) {
      month = {
        name: monthNames[bmonth.getMonth()],
        start: bmonth.valueOf(),
        end: 0
      };
      bmonth.setMonth(bmonth.getMonth() + 1);
      month.end = bmonth.valueOf() - 1;
      $scope.months.push(month);
    }
    return $scope.allmonths.end = bmonth.valueOf();
  });

}).call(this);