// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').directive('tenantDetails', function(alert) {
    return {
      restrict: 'EA',
      template: require("./tenant-details.html").default,
      replace: true,
      scope: {
        title: '@'
      },
      link: function(scope, elem, attrs) {
        var fieldName, tenantCopy;
        scope.editing = false;
        fieldName = scope.title;
        tenantCopy = null;
        scope.edit = function(tenant) {
          tenantCopy = JSON.parse(JSON.stringify(tenant));
          return tenant.editing = true;
        };
        scope.data = function() {
          var property;
          property = scope.$parent.property;
          if (property && property.item && property.item.$case && property.item.$case.item) {
            return property.item.$case.item.Tenants;
          }
        };
        scope.confirm = function(tenant) {
          //save to database
          scope.$parent.property.item.$case.save();
          alert.log('Contact details updated');
          return tenant.editing = false;
        };
        return scope.cancel = function(tenant) {
          if (tenantCopy) {
            Object.assign(tenant, tenantCopy);
            tenantCopy = null;
          }
          return tenant.editing = false;
        };
      }
    };
  });

}).call(this);
