// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsTemplateCtrl', function($scope, $stateParams, $state, $http) {
    var cb;
    $scope.type = $stateParams.type;
    cb = function(template) {
      if (template) {
        return $scope.template.locked = true;
      }
    };
    if ($stateParams.type === 'email') {
      $scope.lang = 'pug';
      $scope.template = $scope.single('maintenance_leads:emailtemplates', $stateParams.id, cb);
    } else {
      $scope.lang = 'text';
      $scope.template = $scope.single('maintenance_leads:smstemplates', $stateParams.id, cb);
    }
    $scope.save = function() {
      if ($scope.myForm.$valid) {
        $scope.template.save();
        return $state.go('maintenance_leads_setup');
      }
    };
    $scope.cancel = function() {
      return $state.go('maintenance_leads_setup');
    };
    return $scope.defaultData = {
      address: "22 Flixton Road, Urmston, M41 5AA",
      address1: "22 Flixton Road",
      address2: "Urmston",
      booked: "5da63ec84cba301a96c94984",
      isBooked: true,
      cfpJobNumber: "986754",
      contractorArranged: "yes",
      date: 1571176184159,
      details: "My boiler will not turn on and has no pressure",
      landlordInformed: "yes",
      modifiedAt: 1571177277049,
      modifiedBy: "5da63cde4cba301a96c94983",
      postcode: "M41 5AA",
      repliedToTenant: "yes",
      source: "telephone",
      tenant: "Mr Richard Antrobus",
      tenantEmail: "richard@vitalspace.co.uk",
      tenantFirstName: "Richard",
      tenantLastName: "Antrobus",
      tenantPhone: "01617477807",
      tenantTitle: "Mr",
      title: "Boiler leaking",
      _id: "5da63efb4cba301a96c94985"
    };
  });

}).call(this);
