// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_template', {
      url: '/maintenance_leads/template/:id/:type',
      template: require("./template.html").default,
      controller: 'maintenance_leadsTemplateCtrl',
      data: {
        title: 'Vitalspace Maintenance Leads - Template',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin']
      }
    });
  });

}).call(this);
