// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').filter('currencyFormat', function($sce) {
    return function(val) {
      var bits;
      if (angular.isDefined(val)) {
        if (val.toString().indexOf('.') !== -1) {
          bits = val.toString().split('.');
          val = bits[0] + '.<sub>' + bits[1] + '</sub>';
        }
      } else {
        val = '';
      }
      return $sce.trustAs('html', val.toString());
    };
  });

}).call(this);
