// Generated by CoffeeScript 2.5.1
(function() {
  angular.module('vs-lettings').filter('flatten', function() {
    return function(input) {
      var group, i, j, len, len1, milestone, output;
      output = [];
      if (input) {
        for (i = 0, len = input.length; i < len; i++) {
          group = input[i];
          for (j = 0, len1 = group.length; j < len1; j++) {
            milestone = group[j];
            output.push(milestone);
          }
        }
      }
      return output;
    };
  });

}).call(this);
