// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  var e;

  angular.module('vs-agency', ['ndx', 'ui.router', 'agency-date-swiper', 'multi-check', 'ui.gravatar', 'ngFileUpload']).config(function(gravatarServiceProvider, AuthProvider) {
    gravatarServiceProvider.defaults = {
      size: 40,
      "default": 'mm',
      rating: 'pg'
    };
  }).run(function($rootScope, $state, AgencyProgressionPopup, $http, $transitions, ndxModal, env) {
    var root;
    $http.defaults.headers.common.Authorization = `Bearer ${env.PROPERTY_TOKEN}`;
    $rootScope.state = function(route) {
      if ($state && $state.current) {
        if (Object.prototype.toString.call(route) === '[object Array]') {
          return route.indexOf($state.current.name) !== -1;
        } else {
          return route === $state.current.name;
        }
      }
      return false;
    };
    $transitions.onBefore({}, function(trans) {
      if (trans.$from().name) {
        AgencyProgressionPopup.hide();
        return $('body').removeClass(`${trans.$from().name}-page`);
      }
    });
    $transitions.onFinish({}, function(trans) {
      if (trans.$to().name) {
        return $('body').addClass(`${trans.$to().name}-page`);
      }
    });
    root = Object.getPrototypeOf($rootScope);
    root.generateId = function(len) {
      var i, letters, output;
      letters = "abcdefghijklmnopqrstuvwxyz0123456789";
      output = '';
      i = 0;
      while (i++ < len) {
        output += letters[Math.floor(Math.random() * letters.length)];
      }
      return output;
    };
    root.hidePopup = function(ev) {
      return AgencyProgressionPopup.hide();
    };
    return root.modal = function(args) {
      var backdrop, controller, modalInstance, size;
      size = args.size || 'large';
      controller = args.controller || 'YesNoCancelCtrl';
      backdrop = args.backdrop || 'static';
      modalInstance = ndxModal.open({
        template: args.template,
        windowClass: size,
        controller: controller,
        backdrop: backdrop,
        resolve: {
          data: function() {
            return args.data;
          }
        }
      });
      return modalInstance.result;
    };
  }).config(function($locationProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/');
    $locationProvider.html5Mode(true);
  });

  try {
    angular.module('ndx');
  } catch (error) {
    e = error;
    angular.module('ndx', []); //ndx module stub
  }

}).call(this);
