// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').controller('agencyMarketingCtrl', function($scope, $http) {
    $scope.submitNewSales = function() {
      $scope.submitted = true;
      if ($scope.newSalesEmail.$valid) {
        return $http.post($http.sites["agency"].url + '/api/properties/send-new-sales-email', {
          newSales: $scope.newSales
        }, $http.sites["agency"].config).then(function() {
          $scope.salesEmailSent = true;
          return $scope.submitted = false;
        });
      }
    };
    $scope.submitNewLettings = function() {
      $scope.submitted = true;
      if ($scope.newLettingsEmail.$valid) {
        return $http.post($http.sites["agency"].url + '/api/properties/send-new-lettings-email', {
          newLettings: $scope.newLettings
        }, $http.sites["agency"].config).then(function() {
          $scope.lettingsEmailSent = true;
          return $scope.submitted = false;
        });
      }
    };
    return $scope.submitReduction = function() {
      $scope.submitted = true;
      if ($scope.reductionEmail.$valid) {
        return $http.post($http.sites["agency"].url + '/api/properties/send-reduction-email', {
          reduction: $scope.reduction
        }, $http.sites["agency"].config).then(function() {
          $scope.reductionEmailSent = true;
          return $scope.submitted = false;
        });
      }
    };
  });

}).call(this);
