// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings').config(function($stateProvider) {
    return $stateProvider.state('lettings_dashboard', {
      url: '/lettings',
      template: '<lettings-dashboard></lettings-dashboard>',
      data: {
        title: 'Vitalspace Lettings - Dashboard'
      }
    });
  });

}).call(this);
