// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').directive('maintenanceleadsDashboard', function(Sorter) {
    return {
      template: require("./dashboard.html").default,
      scope: {},
      link: (scope) => {
        var now, yesterday;
        now = new Date();
        yesterday = new Date().setHours(now.getHours() - 24);
        scope.maintenanceToday = scope.list('maintenance_leads:issues', {
          page: 1,
          pageSize: 10,
          where: {
            date: {
              $gt: yesterday.valueOf()
            },
            search: {
              $like: ''
            },
            statusName: 'Reported',
            $or: [
              {
                inspectionWorks: {
                  $ne: true
                }
              },
              {
                inspectionWorks: {
                  $null: true
                }
              }
            ]
          },
          sort: 'date',
          sortDir: 'DESC'
        });
        scope.maintenanceToday.sort = Sorter.create(scope.maintenanceToday.args);
        scope.maintenanceOutstanding = scope.list('maintenance_leads:issues', {
          page: 1,
          pageSize: 10,
          where: {
            date: {
              $lte: yesterday.valueOf()
            },
            search: {
              $like: ''
            },
            statusName: 'Reported',
            $or: [
              {
                inspectionWorks: {
                  $ne: true
                }
              },
              {
                inspectionWorks: {
                  $null: true
                }
              }
            ]
          },
          sort: 'date',
          sortDir: 'DESC'
        });
        scope.maintenanceOutstanding.sort = Sorter.create(scope.maintenanceOutstanding.args);
        scope.worksOutstanding = scope.list('maintenance_leads:issues', {
          page: 1,
          pageSize: 10,
          where: {
            statusName: 'Booked',
            search: {
              $like: ''
            },
            status: {
              booked: true,
              completed: false,
              invoiced: false
            },
            moveOutWorks: {
              $null: true
            },
            $or: [
              {
                inspectionWorks: {
                  $ne: true
                }
              },
              {
                inspectionWorks: {
                  $null: true
                }
              }
            ]
          },
          sort: 'date',
          sortDir: 'DESC'
        });
        scope.worksOutstanding.sort = Sorter.create(scope.worksOutstanding.args);
        scope.invoiceOutstanding = scope.list('maintenance_leads:issues', {
          page: 1,
          pageSize: 10,
          where: {
            statusName: 'Booked',
            search: {
              $like: ''
            },
            status: {
              completed: true,
              booked: true,
              invoiced: false
            },
            $or: [
              {
                inspectionWorks: {
                  $ne: true
                }
              },
              {
                inspectionWorks: {
                  $null: true
                }
              }
            ]
          },
          sort: 'date',
          sortDir: 'DESC'
        });
        scope.invoiceOutstanding.sort = Sorter.create(scope.invoiceOutstanding.args);
        scope.moveOutWorks = scope.list('maintenance_leads:issues', {
          page: 1,
          pageSize: 10,
          where: {
            statusName: 'Booked',
            search: {
              $like: ''
            },
            status: {
              booked: true,
              completed: false,
              invoiced: false
            },
            moveOutWorks: true,
            $or: [
              {
                inspectionWorks: {
                  $ne: true
                }
              },
              {
                inspectionWorks: {
                  $null: true
                }
              }
            ]
          },
          sort: 'date',
          sortDir: 'DESC'
        });
        scope.moveOutWorks.sort = Sorter.create(scope.moveOutWorks.args);
        scope.inspectionWorks = scope.list('maintenance_leads:issues', {
          page: 1,
          pageSize: 10,
          where: {
            search: {
              $like: ''
            },
            inspectionWorks: true
          },
          sort: 'date',
          sortDir: 'DESC'
        });
        scope.inspectionWorks.sort = Sorter.create(scope.inspectionWorks.args);
        
        scope.openAddIssueModal = function() {
          return scope.modal({
            template: require('../../modals/add-issue/add-issue.html').default,
            controller: 'maintenance_leadsAddIssueModalCtrl',
            size: 'large',
            data: {}
          }).then(function(newIssue) {
            if (newIssue) {
              scope.maintenanceToday.refresh();
              scope.maintenanceOutstanding.refresh();
            }
          });
        };
        
        scope.openAddWorksOrderModal = function() {
          return scope.modal({
            template: require('../../modals/add-works-order/add-works-order.html').default,
            controller: 'maintenance_leadsAddWorksOrderModalCtrl',
            size: 'large',
            data: {}
          }).then(function(newWorksOrder) {
            if (newWorksOrder) {
              scope.worksOutstanding.refresh();
              scope.invoiceOutstanding.refresh();
            }
          });
        };
        
        return true;
      }
    }
  });

}).call(this);
