// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_dashboard', {
      url: '/maintenance_leads',
      template: '<maintenanceleads-dashboard></maintenanceleads-dashboard>',
      data: {
        title: 'Vitalspace Mainenance Leads - Dashboard'
      }
    });
  });

}).call(this);
