// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    return $stateProvider.state('agency_agreed', {
      url: '/agency/agreed',
      template: require("./agreed.html").default,
      controller: 'agencyAgreedCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Agreed',
		auth: ['agency:agency', 'agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
  });

}).call(this);
