// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').directive('maintenanceTask', function(MaintenanceTaskPopup) {
    return {
      restrict: 'EA',
      template: require("./task.html").default,
      replace: true,
      link: function(scope, elem, attrs) {
        return scope.openTask = function(task, ev) {
          MaintenanceTaskPopup.setTask(task);
          MaintenanceTaskPopup.show(elem);
          return ev.stopPropagation();
        };
      }
    };
  });

  /*
task = task or {}
task.duration = task.duration or new Date 3600000
task.assignedTo = task.assignedTo or scope.selectedUser
task.status = task.status or 'quote'
task.createdDate = task.createdDate or new Date().valueOf()
task.createdBy = task.createdBy or scope.auth.getUser()
scope.modal
  template: 'task'
  controller: 'maintenanceTaskCtrl'
  data: 
    task: task
    maintenance: scope.maintenance
.then (result) ->
  true
, (err) ->
  false
*/

}).call(this);
