// Generated by CoffeeScript 2.5.1
(function () {
  'use strict';
  angular.module('vs-leads').controller('leadsHistoryCtrl', function ($scope, $http, Sorter) {
    var where;
    where = {
      $or: [
        {
          deleted: {
            $nn: true
          }
        },
        {
          booked: {
            $nn: true
          }
        }
      ],
      roleType: 'Selling'
    };
    $scope.history = $scope.list('leads:leads', {
      where: where,
      pageSize: 25,
      page: 1,
      sort: 'date',
      sortDir: 'DESC'
    });
    $scope.allhistory = $scope.list('leads:leads', {
      where: where,
      page: 1,
      pageSize: 0
    });
    $scope.sort = Sorter.create($scope.history.args);
    $scope.restore = function (lead) {
      return $http.post($http.sites["leads"].url + `/api/leads/${lead._id}`, {
        deleted: null,
        booked: null
      }, $http.sites.leads.config);
    };
    
    // Add Lead Modal function
    $scope.openAddLeadModal = function(roleType) {
      const modalTemplate = require('../../modals/add-lead/add-lead.html').default;
      $scope.modal({
        template: modalTemplate,
        controller: 'addLeadModalCtrl',
        data: { roleType: roleType }
      });
    };
  });

}).call(this);
