// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-agency').controller('agencyDashboardIncomeCtrl', function($scope, $state, data, ndxModalInstance) {
    $scope.limit = 10;
    $scope.page = 1;
    $scope.data = data;
    $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
    $scope.yes = function() {
      return ndxModalInstance.close();
    };
    $scope.no = function() {
      return ndxModalInstance.close();
    };
    $scope.Math = Math;
    return $scope.go = function(property) {
      ndxModalInstance.close();
      return $state.go('agency_case', {
        roleId: property.roleId
      });
    };
  });

}).call(this);
