// Generated by CoffeeScript 2.6.0
(function() {
  'use strict';
  angular.module('vs-agency').config(function($stateProvider) {
    $stateProvider.state('agency_offer', {
      url: '/agency/offer/:id',
      template: require("./offer.html").default,
      controller: 'agencyOfferCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Offer',
		    auth: ['agency:agency', 'agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
    $stateProvider.state('agency_offer-roleid', {
      url: '/agency/offer/roleid/:roleid',
      template: require("./offer.html").default,
      controller: 'agencyOfferCtrl',
      data: {
        title: 'Vitalspace Conveyancing - Offer',
		    auth: ['agency:agency', 'agency:admin', 'agency:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['agency:agency', 'agency:admin', 'agency:superadmin']);
        }
      }
    });
  });

}).call(this);
