// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsContractorsCtrl', function($scope, Sorter, alert) {
    $scope.page = 1;
    $scope.limit = 15;
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.contractors = $scope.list('maintenance_leads:contractors', {
      sort: 'name',
      sortDir: 'ASC'
    }, function(contractors) {
      var contractor, i, len, ref, results;
      ref = contractors.items;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        contractor = ref[i];
        results.push(contractor.issues = $scope.list('maintenance_leads:issues', {
          where: {
            statusName: 'Booked',
            $or: [
              {
                booked: contractor._id
              },
              {
                contractorName: contractor.name
              }
            ]
          }
        }));
      }
      return results;
    });
    $scope.contractors.sort = Sorter.create($scope.contractors.args);
    $scope.openContractorModal = function(contractor) {
      const modalTemplate = `
        <div class="modal contractor-modal">
          <div class="modal-header">
            <h2>{{contractor.item._id ? 'Edit' : 'New'}} Contractor</h2>
          </div>
          <div class="modal-body">
            <form name="myForm" novalidate="novalidate" autocomplete="off" ng-submit="save()">
              <div class="form-section">
                <div ng-class="{warning: submitted && myForm.name.$invalid}" class="form-item c-input">
                  <label class="label">Name</label>
                  <input type="text" name="name" ng-model="contractor.item.name" placeholder="Contractor Name" title="Name" required/>
                </div>
                <div ng-class="{warning: submitted && myForm.phone.$invalid}" class="form-item c-input">
                  <label class="label">Phone</label>
                  <input type="text" name="phone" ng-model="contractor.item.phone" placeholder="Phone Number" title="Phone"/>
                </div>
                <div ng-class="{warning: submitted && myForm.email.$invalid}" class="form-item c-input">
                  <label class="label">Email</label>
                  <input type="email" name="email" ng-model="contractor.item.email" placeholder="Email Address" title="Email"/>
                </div>
              </div>
            </div>
            <div class="controls modal-footer">
              <button type="submit" class="button button-alt" ng-disabled="myForm.$pristine">Save</button>
              <button type="button" ng-click="cancel()" class="button cancel">Cancel</button>
            </div>
          </form>
          <a class="close-reveal-modal" ng-click="cancel()">&times;</a>
        </div>
      `;
      
      $scope.modal({
        template: modalTemplate,
        controller: 'maintenance_leadsContractorModalCtrl',
        data: {
          contractor: contractor,
          contractors: $scope.contractors
        }
      });
    };
    $scope.openContractorIssues = function(contractor) {
      if (!contractor.open) {
        const modalTemplate = `
          <div class="modal properties-modal">
            <div class="modal-header">
              <h2>{{contractor.name}} Issues</h2>
              <div class="snapshot">
                <div class="snapshot-item">
                  <div class="snapshot-label">Total Issues</div>
                  <div class="snapshot-value">{{contractor.issues.total}}</div>
                </div>
              </div>
            </div>
            <div class="properties-list">
              <div class="property-card" ng-repeat="issue in contractor.issues.items track by issue._id">
                <div class="property-header">
                  <div class="property-number">{{$index + 1}}</div>
                  <div class="property-address">
                    <a ui-sref="maintenance_leads_issue({_id:issue._id})">{{issue.address}}</a>
                    <div class="title">{{issue.title}}</div>
                  </div>
                </div>
              </div>
            </div>
            <a class="close-reveal-modal" ng-click="cancel()">&times;</a>
          </div>
        `;
        
        contractor.open = true;
        $scope.modal({
          template: modalTemplate,
          controller: 'maintenance_leadsContractorIssuesCtrl',
          data: {
            contractor: contractor
          }
        }).then(() => {
          contractor.open = false;
        }, () => {
          contractor.open = false;
        });
      }
    };
    return $scope.deleteContractor = function(contractor) {
      return $scope.modal({
        template: require('../../modals/contractor-delete/contractor-delete.html').default,
        controller: 'maintenance_leadsIssueDeleteCtrl',
        size: 'small'
      }).then(function() {
        $scope.contractors.delete(contractor);
        $state.go('contractors');
        return alert.log('Contractor deleted');
      }, function(err) {
        return;
      });
    };
  });

  angular.module('vs-maintenance-leads').controller('maintenance_leadsContractorIssuesCtrl', function($scope, data, ndxModalInstance) {
    $scope.contractor = data.contractor;
    
    $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

  angular.module('vs-maintenance-leads').controller('maintenance_leadsContractorModalCtrl', function($scope, data, ndxModalInstance, alert) {
    if (data.contractor) {
      // Editing existing contractor - load the full object
      $scope.contractor = $scope.single('maintenance_leads:contractors', data.contractor._id);
    } else {
      // Creating new contractor
      $scope.contractor = $scope.single('maintenance_leads:contractors', {}, function(contractor) {
        contractor.item = {
          name: '',
          phone: '',
          email: ''
        };
      });
    }
    
    $scope.save = function() {
      $scope.submitted = true;
      if ($scope.myForm.$valid) {
        $scope.contractor.save().then(function() {
          alert.log('Contractor saved');
          data.contractors.fetch();
          ndxModalInstance.close();
        }, function(err) {
          alert.error('Error saving contractor');
        });
      }
    };
    
    $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

}).call(this);
