// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_contractors', {
      url: '/maintenance_leads/contractors',
      template: require("./contractors.html").default,
      controller: 'maintenance_leadsContractorsCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - Contractors',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin', 'maintenance_leads:agency']
      }
    });
  });

}).call(this);
