// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').config(function($stateProvider) {
    return $stateProvider.state('maintenance_setup', {
      url: '/maintenance/setup',
      template: require("./setup.html").default,
      controller: 'maintenanceSetupCtrl',
	  data: {
        title: 'Vitalspace Maintenance - Setup',
		auth: ['maintenance:admin', 'maintenance:superadmin']
	  },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['maintenance:admin', 'maintenance:superadmin']);
        }
      }
    });
  });

}).call(this);
