// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').controller('maintenanceSetupCtrl', function($scope, $http, alert) {
    $scope.jobtypes = $scope.single('maintenance:jobtypes', {
      type: 'default'
    });
    $scope.jobCallbacks = [
      {
        name: 'change',
        callback: function() {
          return $scope.jobtypes.save();
        }
      }
    ];
    $scope.users = $scope.list('maintenance:users');
    $scope.addUser = function() {
      $scope.newUser.roles = {};
      $scope.newUser.roles[$scope.newUser.role] = {};
      delete $scope.newUser.role;
      $http.post($http.sites["maintenance"].url + '/api/get-invite-code', $scope.newUser, $http.sites["maintenance"].config).then(function(response) {
        $scope.inviteUrl = response.data;
        return alert.log('Invite sent');
      }, function(err) {
        return $scope.inviteError = err.data;
      });
      return $scope.newUser = {
        role: 'agency'
      };
    };
    return $scope.copyInviteToClipboard = function() {
      $('.invite-url input').select();
      alert.log('Copied to clipboard');
      return document.execCommand('copy');
    };
  });

}).call(this);
