// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').directive('maintenanceTaskPopup', function($http, alert, MaintenanceTaskPopup) {
    return {
      restrict: 'EA',
      template: require("./task-popup.html").default,
      replace: true,
      link: function(scope, elem, attrs) {
        scope.getTask = MaintenanceTaskPopup.getTask;
        scope.getHidden = MaintenanceTaskPopup.getHidden;
        scope.getDateTo = function() {
          var task;
          task = MaintenanceTaskPopup.getTask();
          if (task) {
            return new Date(task.date.valueOf() + (task.duration.valueOf() - (task.duration.getTimezoneOffset() * 60 * 1000)));
          }
        };
        scope.save = function() {
          const task = scope.getTask();
          return $http.post($http.sites["maintenance"].url + `/api/tasks/${scope.getTask()._id || ''}`, scope.getTask(), $http.sites["maintenance"].config).then(function(response) {
            return alert.log('Task updated');
          }, function(err) {
            return false;
          });
        };
        scope.complete = function() {
          scope.getTask().status = 'completed';
          return scope.save();
        };
        return scope.edit = function(task) {
          MaintenanceTaskPopup.hide();
          return scope.modal({
            template: require('../../modals/task/task.html').default,
            controller: 'maintenanceTaskCtrl',
            data: {
              task: task,
              maintenance: scope.maintenance
            }
          }, $http.sites["maintenance"].config).then(function(response) {
            return true;
          }, function(err) {
            return false;
          });
        };
      }
    };
  });

}).call(this);
