// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').config(function($stateProvider) {
    return $stateProvider.state('lettings_setup', {
      url: '/lettings/setup',
      template: require("./setup.html").default,
      controller: 'lettingsSetupCtrl',
      data: {
        title: 'Vitalspace Lettings - Setup',
		auth: ['lettings:admin', 'lettings:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['lettings:admin', 'lettings:superadmin']);
        }
      }
    });
  });

}).call(this);
