// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').controller('lettingsCasesCtrl', function($scope, env) {
    $scope.page = 1;
    $scope.limit = 15;
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.nodeleted = 0;
    $scope.propsOpts = {
      where: {
        RoleStatus: 'OfferAccepted',
        RoleType: 'Letting',
        IncludeStc: true
      },
      transform: {
        items: 'Collection',
        total: 'TotalCount'
      }
    };
    $scope.properties = $scope.list({
      route: `${env.PROPERTY_URL}/search`
    }, $scope.propsOpts, function(properties) {
      var i, len, property, ref, results;
      ref = properties.items;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        property = ref[i];
	    const availableDate = new Date(property.AvailableDate);
	    let availableDateVal = availableDate.valueOf() - (availableDate.getTimezoneOffset() * 60 * 1000);
        property.$case = $scope.single('lettings:properties', property.RoleId + '_' + availableDateVal, function(item) {
          var ref1;
          item.$parent.search = `${item.item.displayAddress}||${item.item.TenantName}||${item.item.LandlordName}`;
          item.$parent.milestoneStatus = item.item.milestoneStatus;
          
          // Generate icon from title if not present
          if (item.item.milestone && !item.item.milestone.icon && item.item.milestone.title) {
            item.item.milestone.icon = item.item.milestone.title.toLowerCase()
              .replace(/&/g, 'and')
              .replace(/[^a-z0-9\s-]/g, '')
              .replace(/\s+/g, '-')
              .replace(/-+/g, '-');
          }
          
          if (item.item.progressions && item.item.progressions.length) {
            item.$parent.estCompletedTime = item.item.progressions[0].milestones[item.item.progressions[0].milestones.length - 1][0].estCompletedTime;
          }
          if (item.$parent.estCompletedTime < new Date().valueOf()) {
            item.$parent.needsDate = true;
          }
          item.$parent.deleted = ((ref1 = item.item.override) != null ? ref1.deleted : void 0) || false;
          if (item.$parent.deleted) {
            return $scope.nodeleted++;
          }
        });
        results.push(property.$case.$parent = property);
      }
      return results;
    });
    return $scope.hasRequest = function(property) {
      var i, len, ref, request;
      if ($scope.auth.checkRoles(['superadmin', 'admin']) && property.$case.item && property.$case.item.advanceRequests && property.$case.item.advanceRequests.length) {
        ref = property.$case.item.advanceRequests;
        for (i = 0, len = ref.length; i < len; i++) {
          request = ref[i];
          if (!request.dismissed && !request.applied) {
            return true;
          }
        }
      }
      return false;
    };
  });

}).call(this);
