// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').directive('leadsDashboard', function(ndxModal) {
    return {
      template: require("./dashboard.html").default,
      scope: {},
      link: (scope) => {
        scope.openAddLeadModal = function(roleType) {
          const modalTemplate = require('../../modals/add-lead/add-lead.html').default;
          const modalInstance = ndxModal.open({
            template: modalTemplate,
            windowClass: 'large',
            controller: 'addLeadModalCtrl',
            backdrop: 'static',
            resolve: {
              data: function() {
                return { roleType: roleType };
              }
            }
          });
          return modalInstance.result;
        };
        
        return scope.auth.onUser(function() {
          scope.sellingToday = scope.list('leads:leads', {
            preRefresh: function(args) {
              var end, start;
              end = new Date();
              start = new Date();
              start.setHours(0, 0, 0, 0);
              return args.where = {
                date: {
                  $gte: start.valueOf(),
                  $lte: end.valueOf()
                },
                roleType: 'Selling',
                booked: null,
                deleted: null
              };
            },
            page: 1,
            pageSize: 0
          });
          scope.sellingOutstanding = scope.list('leads:leads', {
            preRefresh: function(args) {
              var startOfToday;
              startOfToday = new Date();
              startOfToday.setHours(0, 0, 0, 0);
              return args.where = {
                date: {
                  $lt: startOfToday.valueOf()
                },
                roleType: 'Selling',
                booked: null,
                deleted: null
              };
            },
            page: 1,
            pageSize: 0
          });
          scope.lettingToday = scope.list('leads:leads', {
            preRefresh: function(args) {
              var end, start;
              end = new Date();
              start = new Date();
              start.setHours(0, 0, 0, 0);
              return args.where = {
                date: {
                  $gte: start.valueOf(),
                  $lte: end.valueOf()
                },
                roleType: 'Letting',
                booked: null,
                deleted: null
              };
            },
            page: 1,
            pageSize: 0
          });
          scope.lettingOutstanding = scope.list('leads:leads', {
            preRefresh: function(args) {
              var startOfToday;
              startOfToday = new Date();
              startOfToday.setHours(0, 0, 0, 0);
              return args.where = {
                date: {
                  $lt: startOfToday.valueOf()
                },
                roleType: 'Letting',
                booked: null,
                deleted: null
              };
            },
            page: 1,
            pageSize: 0
          });
          scope.valuationToday = scope.list('leads:leads', {
            preRefresh: function(args) {
              var end, start;
              end = new Date();
              start = new Date();
              start.setHours(0, 0, 0, 0);
              return args.where = {
                date: {
                  $gte: start.valueOf(),
                  $lte: end.valueOf()
                },
                roleType: 'Valuation',
                booked: null,
                deleted: null
              };
            },
            page: 1,
            pageSize: 0
          });
          return scope.valuationOutstanding = scope.list('leads:leads', {
            preRefresh: function(args) {
              var startOfToday;
              startOfToday = new Date();
              startOfToday.setHours(0, 0, 0, 0);
              return args.where = {
                date: {
                  $lt: startOfToday.valueOf()
                },
                roleType: 'Valuation',
                booked: null,
                deleted: null
              };
            },
            page: 1,
            pageSize: 0
          });
        });
      }
    }
  });

}).call(this);
