// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').config(function($stateProvider) {
    return $stateProvider.state('leads_dashboard', {
      url: '/leads',
      template: '<leads-dashboard></leads-dashboard>',
      data: {
        title: 'Vitalspace Leads - Dashboard'
      }
    });
  });

}).call(this);
