// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsHistoricCtrl', function($scope, $http, Sorter, DbItem, alert) {
    $scope.dbItem = DbItem;
    $scope.page = 1;
    $scope.limit = 15;
    $scope.mysearch = {
      $like: ''
    };
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.historic = $scope.list('maintenance_leads:issues', {
      page: 1,
      pageSize: $scope.limit,
      sort: 'date',
      sortDir: 'DESC',
      where: {
        $or: [
          {
            deleted: {
              $ne: null
            }
          },
          {
            deleted: null
          }
        ],
        search: $scope.mysearch
      }
    });
    $scope.sort = Sorter.create($scope.historic.args);
    return $scope.restoreIssue = function(issue) {
      return $scope.modal({
        template: require('../../modals/issue-restore/issue-restore.html').default,
        controller: 'maintenance_leadsIssueDeleteCtrl',
        size: 'small'
      }).then(function() {
        return $http.get($http.sites["maintenance_leads"].url + 'api/restore/' + issue._id, $http.sites["maintenance_leads"].config).then(function() {
          return alert.log('Issue restored');
        }, function(err) {
          return;
        });
      }, function(err) {
        return;
      });
    };
  });

}).call(this);
