// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_historic', {
      url: '/maintenance_leads/historic',
      template: require("./historic.html").default,
      controller: 'maintenance_leadsHistoricCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - Historic Issues',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin', 'maintenance_leads:agency']
      }
    });
  });

}).call(this);
