// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance').config(function($stateProvider) {
    return $stateProvider.state('maintenance_dashboard', {
      url: '/maintenance',
      template: require("./dashboard.html").default,
      controller: 'maintenanceDashboardCtrl',
      data: {
        title: 'Vitalspace Maintenance - Calendar'
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise();
        }
      }
    });
  });

}).call(this);
