// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('ndx').filter('byStatus', function() {
    return function(input, filters) {
      var hasFilter, i, item, key, len, output;
      if (input && filters) {
        hasFilter = false;
        for (key in filters) {
          if (filters[key]) {
            hasFilter = true;
            break;
          }
        }
        if (!hasFilter) {
          return input;
        }
        output = [];
        for (i = 0, len = input.length; i < len; i++) {
          item = input[i];
          if (filters[item.status]) {
            output.push(item);
          }
        }
        return output;
      }
      return input;
    };
  });

}).call(this);
