// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsAddWorksOrderModalCtrl', function($scope, $http, ndxModalInstance, data, alert) {
    $scope.data = data || {};
    $scope.submitted = false;
    $scope.forms = {};
    
    // Initialize works order object
    if ($scope.data.worksOrder) {
      $scope.worksOrder = $scope.data.worksOrder;
    } else {
      $scope.worksOrder = {
        date: new Date(),
        priority: 'Low',
        moveOutWorks: 'Tenancy Issue'
      };
      
      // If coming from an issue, pre-populate data
      if ($scope.data.issue) {
        $scope.worksOrder.issueId = $scope.data.issue._id;
        $scope.worksOrder.address = $scope.data.issue.address1 + ', ' + ($scope.data.issue.address2 ? $scope.data.issue.address2 + ', ' : '') + $scope.data.issue.postcode;
        $scope.worksOrder.tenant = $scope.data.issue.tenantFirstName + ' ' + $scope.data.issue.tenantLastName;
        $scope.worksOrder.tenantPhone = $scope.data.issue.tenantPhone;
        $scope.worksOrder.tenantEmail = $scope.data.issue.tenantEmail;
        $scope.worksOrder.issueTitle = $scope.data.issue.title;
        $scope.worksOrder.issueDetails = $scope.data.issue.details;
      }
    }
    
    // Load contractors
    $scope.contractors = $scope.list('maintenance_leads:contractors', {
      page: 1,
      pageSize: 1000,
      sort: 'name',
      sortDir: 'ASC'
    });
    
    $scope.submit = function() {
      $scope.submitted = true;
      
      if (!$scope.forms.worksOrderForm.$valid) {
        return;
      }
      
      const contractor = $scope.contractors.items.find(c => c._id === $scope.worksOrder.contractor);
      if (!contractor) {
        alert.log('Please select a contractor');
        return;
      }
      
      const htmldiv = document.createElement('div');
      const newIssue = !$scope.data.issue;
      
      htmldiv.innerHTML = `
        <style>
          p, h1 {margin:0!important}
          h3 {margin:5px 0 0 0!important}
          h2 {margin:10px 0 0 0!important}
          .worksorder-body {
            height: 950px;
            min-height: 950px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
          }
          img {
            max-width: 100%;
          }
          p {
            font-size: 1.4rem!important;
          }
          h1 {
            font-size: 1.8rem!important;
          }
          h2 {
            font-size: 1.6rem!important;
          }
          h3 {
            font-size: 1.4rem!important;
          }
        </style>
        <div class="worksorder-body">
          <div class="worksorder-main">
            <center><img src="/public/img/worksorder-header.jpeg" /></center>
            <h3><strong>${contractor.name}</strong></h3>
            <p>${contractor.phone || ''}</p>
            <p>${contractor.email || ''}</p>
            <h2>VITALSPACE</h2>
            <h1 class="orange">WORKSHEET</h1>
            <h3><strong>Date</strong></h3>
            <p>${new Date($scope.worksOrder.date).toDateString()}</p>
            <h3><strong>Priority</strong></h3>
            <p>${$scope.worksOrder.priority || ''}</p>
            <h2 class="orange">Property Address</h2>
            <p>${(newIssue ? $scope.worksOrder.address : $scope.data.issue.address) || ''}</p>
            <h2 class="orange">Tenant Details</h2>
            <p>${(newIssue ? $scope.worksOrder.tenant : ($scope.data.issue.tenantFirstName + ' ' + $scope.data.issue.tenantLastName)) || ''}</p>
            <p>${(newIssue ? $scope.worksOrder.tenantPhone : $scope.data.issue.tenantPhone) || ''}</p>
            <p>${(newIssue ? $scope.worksOrder.tenantEmail : $scope.data.issue.tenantEmail) || ''}</p>
            <h2 class="orange">Issue Details</h2>
            <h3><strong>Issue Title</strong></h3>
            <p>${(newIssue ? $scope.worksOrder.issueTitle : $scope.data.issue.title) || ''}</p>
            <h3><strong>Fault Detail</strong></h3>
            <p>${(newIssue ? $scope.worksOrder.issueDetails : $scope.data.issue.details) || ''}</p>
      `;
      
      if ($scope.worksOrder.notes) {
        htmldiv.innerHTML += `
          <h3><strong>Additional Notes</strong></h3>
          <p>${$scope.worksOrder.notes}</p>
        `;
      }
      
      htmldiv.innerHTML += `
          </div>
          <div class="worksorder-footer">
            <center><img src="/public/img/worksorder-footer.jpeg" /></center>
          </div>
        </div>
      `;
      
      const htmlContent = htmldiv;
      const pdfOptions = {
        margin: 10,
        filename: 'generated.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 1 },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      };
      
      html2pdf()
        .from(htmlContent)
        .set(pdfOptions)
        .outputPdf()
        .toPdf()
        .get('pdf')
        .then(pdf => {
          const pdfBlob = pdf.output('blob');
          const reader = new FileReader();
          
          reader.onload = function() {
            const pdfBase64 = reader.result.split(',')[1];
            const pdfFileName = `${parseInt(new Date().getTime().toString() + (Math.random() * 9999)).toString(20)}.pdf`;
            const pdfData = {
              base64: pdfBase64,
              filename: pdfFileName,
            };
            
            $http.post($http.sites["main"].url + '/api/upload-pdf', pdfData, $http.sites["main"].config)
              .then(response => {
                if (response.status === 200) {
                  alert.log('Works order created successfully');
                  
                  const pdfUrl = `https://vitalspace-worksorders.s3.eu-west-1.amazonaws.com/${pdfFileName}`;
                  const contractorName = contractor.name;
                  
                  // If there's an existing issue, update it to be a works order
                  if ($scope.data.issue && $scope.data.issue._id) {
                    $scope.data.issue.notes = $scope.data.issue.notes || [];
                    $scope.data.issue.notes.push({
                      date: new Date().getTime(),
                      item: 'Note',
                      side: '',
                      text: `## **Works order created**  \n<${pdfUrl}>`,
                      user: $scope.auth.getUser()
                    });
                    
                    // Update issue to appear as a works order
                    const issue = $scope.single('maintenance_leads:issues', { _id: $scope.data.issue._id }, function(issueObj) {
                      if (issueObj && issueObj.item) {
                        issueObj.item.notes = $scope.data.issue.notes;
                        issueObj.item.statusName = 'Booked';
                        issueObj.item.status = {
                          booked: true,
                          completed: false,
                          invoiced: false
                        };
                        issueObj.item.contractorName = contractorName;
                        if ($scope.worksOrder.moveOutWorks === 'Move Out Issue') {
                          issueObj.item.moveOutWorks = true;
                        }
                        issueObj.save();
                      }
                    });
                    
                    // Create task for the works order
                    const dateStr = new Date($scope.worksOrder.date).toISOString().replace('T00', 'T09');
                    const task = {
                      "date": dateStr,
                      "duration": 1800000,
                      "status": {
                        "booked": true
                      },
                      "issue": $scope.data.issue._id,
                      "title": $scope.data.issue.title || $scope.worksOrder.issueTitle || "",
                      "address": $scope.data.issue.address || $scope.worksOrder.address || "",
                      "contractor": $scope.worksOrder.contractor,
                      "dateVal": new Date(dateStr).valueOf(),
                      "cfpJobNumber": "",
                      "contractorName": contractorName,
                      "moveOutWorks": $scope.worksOrder.moveOutWorks === 'Move Out Issue'
                    };
                    
                    $http.post($http.sites["maintenance_leads"].url + `/api/tasks`, task, $http.sites.maintenance_leads.config);
                  } else {
                    // Create a new issue and task for the works order
                    const issueId = Math.floor(Math.random() * 99999999999999999999).toString(36);
                    const issue = {
                      "_id": issueId,
                      "source": "telephone",
                      "postcode": "",
                      "address1": $scope.worksOrder.address || "",
                      "address2": "",
                      "tenantTitle": "Mr",
                      "tenantFirstName": $scope.worksOrder.tenant ? $scope.worksOrder.tenant.split(' ')[0] : "Empty",
                      "tenantLastName": $scope.worksOrder.tenant ? $scope.worksOrder.tenant.split(' ').slice(1).join(' ') || "Empty" : "Empty",
                      "tenantPhone": $scope.worksOrder.tenantPhone || "",
                      "tenantEmail": $scope.worksOrder.tenantEmail || "",
                      "details": $scope.worksOrder.issueDetails || "",
                      "title": $scope.worksOrder.issueTitle || "",
                      "landlordId": "",
                      "date": new Date().valueOf(),
                      "address": $scope.worksOrder.address || "",
                      "tenant": $scope.worksOrder.tenant || "",
                      "statusName": "Booked",
                      "landlordName": "Empty",
                      "landlordPhone": "Empty",
                      "landlordEmail": "Empty",
                      "quoteContractor": "0",
                      "quoteVitalSpace": "0",
                      "repliedToTenant": "no",
                      "landlordInformed": "no",
                      "contractorArranged": "no",
                      "moveOutWorks": $scope.worksOrder.moveOutWorks === 'Move Out Issue',
                      "notes": [{
                        date: new Date().getTime(),
                        item: 'Note',
                        side: '',
                        text: `## **Works order created**  \n<${pdfUrl}>`,
                        user: $scope.auth.getUser()
                      }],
                      "contractorName": contractorName,
                      "status": {
                        "booked": true,
                        "completed": false,
                        "invoiced": false
                      },
                      "cfpJobNumber": ""
                    };
                    
                    $http.post($http.sites["maintenance_leads"].url + `/api/issues/${issueId}`, issue, $http.sites.maintenance_leads.config);
                    
                    // Create task for the works order
                    const dateStr = new Date($scope.worksOrder.date).toISOString().replace('T00', 'T09');
                    const task = {
                      "date": dateStr,
                      "duration": 1800000,
                      "status": {
                        "booked": true
                      },
                      "issue": issueId,
                      "title": $scope.worksOrder.issueTitle || "",
                      "address": $scope.worksOrder.address || "",
                      "contractor": $scope.worksOrder.contractor,
                      "dateVal": new Date(dateStr).valueOf(),
                      "cfpJobNumber": "",
                      "contractorName": contractorName,
                      "moveOutWorks": $scope.worksOrder.moveOutWorks === 'Move Out Issue'
                    };
                    
                    $http.post($http.sites["maintenance_leads"].url + `/api/tasks`, task, $http.sites.maintenance_leads.config);
                  }
                  
                  ndxModalInstance.close({ pdfUrl: pdfUrl });
                } else {
                  alert.log('Error uploading PDF');
                }
              })
              .catch(error => {
                console.error('Error uploading PDF:', error);
                alert.log('Error uploading PDF');
              });
          };
          
          reader.readAsDataURL(pdfBlob);
        });
    };
    
    $scope.cancel = function() {
      ndxModalInstance.dismiss();
    };
  });

}).call(this);
