// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_contractor', {
      url: '/maintenance_leads/contractor/:_id',
      template: require("./contractor.html").default,
      controller: 'maintenance_leadsContractorCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - Contractor',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin', 'maintenance_leads:agency']
      }
    });
  });

}).call(this);
