// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsContractorCtrl', function($scope, $stateParams) {
    return $scope.contractor = $scope.single('maintenance_leads:contractors', $stateParams);
  });

}).call(this);
