// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadsSetupCtrl', function($scope, $http, $filter, $timeout, alert) {
    $scope.editor = true;
    $scope.newUser = {
      role: 'agency'
    };
    $scope.users = $scope.list('maintenance_leads:users');
    $scope.emailTemplates = $scope.list('maintenance_leads:emailtemplates');
    $scope.smsTemplates = $scope.list('maintenance_leads:smstemplates');
    $scope.addUser = function() {
      $scope.newUser.roles = {};
      $scope.newUser.roles[$scope.newUser.role] = {};
      delete $scope.newUser.role;
      $http.post($http.sites["maintenance_leads"].url + '/api/get-invite-code', $scope.newUser, $http.sites["maintenance_leads"].config).then(function(response) {
        $scope.inviteUrl = response.data;
        return alert.log('Invite sent');
      }, function(err) {
        return $scope.inviteError = err.data;
      });
      return $scope.newUser = {
        role: 'agency'
      };
    };
    $scope.deleteUser = function(user) {
      return $scope.modal({
        template: require('../../modals/user-delete/user-delete.html').default,
        controller: 'maintenance_leadsIssueDeleteCtrl',
        size: 'small'
      }, $http.sites["maintenance_leads"].config).then(function() {
        $scope.users.delete(user);
        return alert.log('User deleted');
      }, function(err) {
        return console.log('err', err);
      });
    };
    $scope.copyInviteToClipboard = function() {
      $('.invite-url input').select();
      alert.log('Copied to clipboard');
      return document.execCommand('copy');
    };
    return $scope.updateStatuses = function() {
      return $http.get($http.sites["maintenance_leads"].url + '/api/update-statuses', $http.sites["maintenance_leads"].config).then(function(res) {
        return alert.log('Updating');
      }, function(err) {
        return console.log(err);
      });
    };
  });

}).call(this);
