// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_setup', {
      url: '/maintenance_leads/setup',
      template: require("./setup.html").default,
      controller: 'maintenance_leadsSetupCtrl',
      data: {
        title: 'Vitalspace Maintenance Leads - Setup',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin']
      }
    });
  });

}).call(this);
