// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings').factory('messagele', function() {
    var fillTemplate, m, messages;
    messages = {
      //menu
      "menu-dashboard": 'Dashboard',
      //forms
      "forms-cancel": 'Cancel',
      "forms-submit": 'Submit'
    };
    fillTemplate = function(template, data) {
      return template.replace(/\{\{(.+?)\}\}/g, function(all, match) {
        var evalInContext;
        evalInContext = function(str, context) {
          return (new Function(`with(this) {return ${str}}`)).call(context);
        };
        return evalInContext(match, data);
      });
    };
    m = function(key, obj) {
      if (messages[key]) {
        if (obj) {
          return fillTemplate(messages[key], obj);
        } else {
          return messages[key];
        }
      }
      if (/-placeholder$/.test(key)) {
        key = key.replace('placeholder', 'label');
        if (messages[key]) {
          if (obj) {
            return fillTemplate(messages[key], obj);
          } else {
            return messages[key];
          }
        }
      }
    };
    return {
      m: m
    };
  }).run(function($rootScope, messagele) {
    var root;
    root = Object.getPrototypeOf($rootScope);
    return root.mle = messagele.m;
  });

}).call(this);
