// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-leads').config(function($stateProvider) {
    return $stateProvider.state('leads_template', {
      url: '/leads/template/:id/:type',
      template: require("./template.html").default,
      controller: 'leadsTemplateCtrl',
      data: {
        title: 'Vitalspace Leads - Template',
        auth: ['leads:superadmin', 'leads:admin']
      }
    });
  });

}).call(this);
