// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-lettings-inner').config(function($stateProvider) {
    return $stateProvider.state('lettings_case', {
      url: '/lettings/case/:roleId',
      template: require("./case.html").default,
      controller: 'lettingsCaseCtrl',
      data: {
        title: 'Vitalspace Lettings - Case',
		auth: ['lettings:agency', 'lettings:admin', 'lettings:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['lettings:agency', 'lettings:admin', 'lettings:superadmin']);
        }
      }
    });
  });

}).call(this);
