// Generated by CoffeeScript 2.6.0
(function() {
  'use strict';
  angular.module('vs-lettings').config(function($stateProvider) {
    $stateProvider.state('lettings_offer', {
      url: '/lettings/offer/:id',
      template: require("./offer.html").default,
      controller: 'lettingsOfferCtrl',
      data: {
        title: 'Vitalspace Lettings - Offer',
		    auth: ['lettings:agency', 'lettings:admin', 'lettings:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['lettings:agency', 'lettings:admin', 'lettings:superadmin']);
        }
      }
    });
    $stateProvider.state('lettings_offer-roleid', {
      url: '/lettings/offer/roleid/:roleid',
      template: require("./offer.html").default,
      controller: 'lettingsOfferCtrl',
      data: {
        title: 'Vitalspace Lettings - Offer',
		    auth: ['lettings:agency', 'lettings:admin', 'lettings:superadmin']
      },
      resolve: {
        user: function(Auth) {
          return Auth.getPromise(['lettings:agency', 'lettings:admin', 'lettings:superadmin']);
        }
      }
    });
  });

}).call(this);
