// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').config(function($stateProvider) {
    return $stateProvider.state('maintenance_leads_landlords', {
      url: '/maintenance_leads/landlords',
      template: require("./landlords.html").default,
      controller: 'maintenance_leadslandlordsCtrl',
      data: {
        title: 'Vitalspace Mainenance Leads - Landlords',
        auth: ['maintenance_leads:superadmin', 'maintenance_leads:admin', 'maintenance_leads:agency']
      }
    });
  });

}).call(this);
