// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  angular.module('vs-maintenance-leads').controller('maintenance_leadslandlordsCtrl', function($scope, Sorter, alert) {
    $scope.page = 1;
    $scope.limit = 15;
    $scope.mysearch = {
      $like: ''
    };
    $scope.pageChange = function() {
      return $('html, body').animate({
        scrollTop: 0
      }, 200);
    };
    $scope.landlords = $scope.list('maintenance_leads:landlords', {
      sort: 'name',
      sortDir: 'ASC',
      where: {
        name: $scope.mysearch
      }
    }, function(landlords) {
      var i, landlord, len, ref, results;
      ref = landlords.items;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        landlord = ref[i];
        results.push(landlord.issues = $scope.list('maintenance_leads:issues', {
          where: {
            statusName: 'Booked',
            $or: [
              {
                booked: landlord._id
              },
              {
                landlordName: landlord.name
              }
            ]
          }
        }));
      }
      return results;
    });
    $scope.landlords.sort = Sorter.create($scope.landlords.args);
    $scope.openLandlordModal = function(landlord) {
      const modalTemplate = `
        <div class="modal landlord-modal">
          <div class="modal-header">
            <h2>{{landlord.item._id ? 'Edit' : 'New'}} Landlord</h2>
          </div>
          <div class="modal-body">
            <form name="myForm" novalidate="novalidate" autocomplete="off" ng-submit="save()">
              <div class="form-section">
                <div ng-class="{warning: submitted && myForm.name.$invalid}" class="form-item c-input">
                  <label class="label">Name</label>
                  <input type="text" name="name" ng-model="landlord.item.name" placeholder="Landlord Name" title="Name" required/>
                </div>
                <div ng-class="{warning: submitted && myForm.phone.$invalid}" class="form-item c-input">
                  <label class="label">Phone</label>
                  <input type="text" name="phone" ng-model="landlord.item.phone" placeholder="Phone Number" title="Phone"/>
                </div>
                <div ng-class="{warning: submitted && myForm.email.$invalid}" class="form-item c-input">
                  <label class="label">Email</label>
                  <input type="email" name="email" ng-model="landlord.item.email" placeholder="Email Address" title="Email"/>
                </div>
                <div ng-if="!landlord.item._id" ng-class="{warning: submitted && myForm.addresses.$invalid}" class="form-item c-select">
                  <label class="label">Properties</label>
                  <div class="input-holder">
                    <select sumoselect="{placeholder:'Select Properties', search:true}" ng-model="landlord.item.addresses" name="addresses" multiple="multiple">
                      <option ng-repeat="address in addresses" value="{{address._id}}">{{ address.name }}</option>
                    </select>
                  </div>
                </div>
                <div ng-if="landlord.item._id" class="form-item">
                  <label class="label">Properties</label>
                  <div class="addresses-list">
                    <div ng-repeat="address in landlord.item.addresses" class="address-item">{{ address }}</div>
                    <div ng-if="!landlord.item.addresses || !landlord.item.addresses.length" class="no-addresses">No properties assigned</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="controls modal-footer">
              <button type="submit" class="button button-alt" ng-disabled="myForm.$pristine">Save</button>
              <button type="button" ng-click="cancel()" class="button cancel">Cancel</button>
            </div>
          </form>
          <a class="close-reveal-modal" ng-click="cancel()">&times;</a>
        </div>
      `;
      
      $scope.modal({
        template: modalTemplate,
        controller: 'maintenance_leadsLandlordModalCtrl',
        data: {
          landlord: landlord,
          landlords: $scope.landlords
        }
      });
    };
    $scope.openLandlordProperties = function(landlord) {
      if (!landlord.open) {
        const modalTemplate = `
          <div class="modal properties-modal">
            <div class="modal-header">
              <h2>{{landlord.name}} Properties</h2>
              <div class="snapshot">
                <div class="snapshot-item">
                  <div class="snapshot-label">Total Properties</div>
                  <div class="snapshot-value">{{landlord.addresses.length}}</div>
                </div>
              </div>
            </div>
            <div class="properties-list">
              <div class="property-card" ng-repeat="address in landlord.addresses track by $index">
                <div class="property-header">
                  <div class="property-number">{{$index + 1}}</div>
                  <div class="property-address">{{address}}</div>
                </div>
              </div>
            </div>
            <a class="close-reveal-modal" ng-click="cancel()">&times;</a>
          </div>
        `;
        
        landlord.open = true;
        $scope.modal({
          template: modalTemplate,
          controller: 'maintenance_leadsLandlordPropertiesCtrl',
          data: {
            landlord: landlord
          }
        }).then(() => {
          landlord.open = false;
        }, () => {
          landlord.open = false;
        });
      }
    };
    return $scope.deletelandlord = function(landlord) {
      return $scope.modal({
        template: require('../../modals/landlord-delete/landlord-delete.html').default,
        controller: 'maintenance_leadsIssueDeleteCtrl',
        size: 'small'
      }).then(function() {
        $scope.landlords.delete(landlord);
        $state.go('maintenance_leads_landlords');
        return alert.log('landlord deleted');
      }, function(err) {
        return console.log('err', err);
      });
    };
  });

  angular.module('vs-maintenance-leads').controller('maintenance_leadsLandlordPropertiesCtrl', function($scope, data, ndxModalInstance) {
    $scope.landlord = data.landlord;
    
    $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

  angular.module('vs-maintenance-leads').controller('maintenance_leadsLandlordModalCtrl', function($scope, data, ndxModalInstance, alert, $timeout) {
    
    $scope.addresses = [];
    
    if (data.landlord) {
      // Editing existing landlord - addresses will be displayed as read-only
      $scope.landlord = $scope.single('maintenance_leads:landlords', data.landlord._id, function(landlord) {
        if (!landlord.item.addresses) {
          landlord.item.addresses = [];
        }
      });
    } else {
      // Creating new landlord - need to load addresses for selection
      $scope.landlord = $scope.single('maintenance_leads:landlords', {}, function(landlord) {
        landlord.item = {
          name: '',
          phone: '',
          email: '',
          addresses: []
        };
      });
      
      // Load addresses list only for new landlords
    var addressesMatch = function(add1, add2) {
      add1 = add1.toUpperCase().replace(/[, ]+/g, '');
      add2 = add2.toUpperCase().replace(/[, ]+/g, '');
      if (!add1 || !add2) {
        return false;
      }
      var i = Math.min(30, Math.min(add1.length, add2.length));
      var good = true;
      while (i-- > 0) {
        good = good && (add1[i] === add2[i]);
      }
      return good;
    };
    
    $scope.issues = $scope.list('maintenance_leads:issues', null, function(issues) {
      if (!issues || !issues.items || !issues.items.length) {
        $scope.addresses = [];
        return;
      }
      
      issues.items.sort(function(a, b) {
        return a.address > b.address ? 1 : -1;
      });
      issues.items.sort(function(a, b) {
        return a.postcode > b.postcode ? 1 : -1;
      });
      
      var currentAddress = "";
      var currentPostcode = "";
      var addresses = [];
      
      issues.items.forEach(function(issue) {
        if (currentPostcode !== issue.postcode.toUpperCase()) {
          addresses.push(currentAddress);
          currentAddress = issue.address;
          currentPostcode = issue.postcode.toUpperCase();
        } else {
          if (addressesMatch(currentAddress, issue.address)) {
            currentAddress = currentAddress.length > issue.address.length ? currentAddress : issue.address;
          } else {
            addresses.push(currentAddress);
            currentAddress = issue.address;
            currentPostcode = issue.postcode.toUpperCase();
          }
        }
      });
      
      $scope.addresses = [];
      addresses.forEach(function(address) {
        if (address && !$scope.addresses.find(function(myaddress) {
          return myaddress.toUpperCase() === address.toUpperCase();
        })) {
          $scope.addresses.push(address);
        }
      });
      
      $scope.addresses.sort(function(a, b) {
        var aClean = a.replace(/\S*\d+\S*|^apartment|^apt|^flat|,/gi, '').trim();
        var bClean = b.replace(/\S*\d+\S*|^apartment|^apt|^flat|,/gi, '').trim();
        return aClean > bClean ? 1 : -1;
      });
      
      $scope.addresses = $scope.addresses.map(function(address) {
        return {
          _id: address,
          name: address
        };
      });
    });
    }
    
    $scope.save = function() {
      $scope.submitted = true;
      if ($scope.myForm.$valid) {
        $scope.landlord.save().then(function() {
          alert.log('Landlord saved');
          data.landlords.fetch();
          ndxModalInstance.close();
        }, function(err) {
          alert.error('Error saving landlord');
        });
      }
    };
    
    $scope.cancel = function() {
      return ndxModalInstance.dismiss();
    };
  });

}).call(this);
