// Generated by CoffeeScript 2.6.0
(function() {
  'use strict';
  angular.module('vs-lettings').controller('lettingsOffersListCtrl', function($scope, $timeout, $http, $state, env) {
    $scope.isHistoric = false;
    if($state && $state.current && $state.current.data && $state.current.data.data && $state.current.data.data.isHistoric) {
      $scope.isHistoric = true;
    }
    $scope.page = 1;
    $scope.limit = 20;
    $scope.options = {
      where: {
        actioned: null
      },
      sort: 'date',
      sortDir: 'DESC'
    }
    if($scope.isHistoric) {
      $scope.options.where.actioned = {$nn:true};
    }
    $scope.offers = $scope.list('leads:offerslettings', $scope.options, (offers) => {
      offers.items.forEach(async offer => {
        offer.date = new Date(offer.date);
        offer.search = (`${offer.address}:${offer.applicant}:${offer.applicant2 || ''}`).toLowerCase();
        // Resize image URL to 590x400 and handle WordPress version numbers
        if(offer.image) {
          const originalImage = offer.image;
          offer.image = offer.image.replace(/-\d+x\d+\./, '-590x400.');
          const versionMatch = offer.image.match(/^(.+\/)(\d{8})-(\d+)(-590x400\.[^/]+)$/);
          if(versionMatch) {
            offer.image = `${versionMatch[1]}${versionMatch[2]}${versionMatch[4]}`;
            offer.imageFallback1 = `${versionMatch[1]}${versionMatch[2]}-1${versionMatch[4]}`;
            offer.imageFallback2 = `${versionMatch[1]}${versionMatch[2]}-${versionMatch[3]}${versionMatch[4]}`;
          } else {
            const noVersionMatch = offer.image.match(/^(.+\/)(.+)(-590x400)(\.[^/]+)$/);
            if(noVersionMatch) {
              offer.imageFallback1 = `${noVersionMatch[1]}${noVersionMatch[2]}${noVersionMatch[4]}`;
            }
          }
        }
      })
    }, $http.sites["agency"].config);
    $scope.formatAddress = (address) => {
      if(!address) return '';
      return address.replace(/, ,/g, ',');
    }
    $scope.formatDate = (date) => {
      return new Date(date).toString().split(/ /g).slice(0, 5).join(' ').replace(/:\d\d$/, '');
    }
    $scope.showHistoric = () => {
      $timeout(() => {
        $scope.offers.args = {
          where: {
            actioned: {
              $nn: true
            }
          },
          sort: 'date',
          sortDir: 'DESC'
        }
        $scope.offers.refreshFn();
      })
    }
    $scope.toggleActioned = (offer) => {
      offer.actioned = offer.actioned ? null : true;
      $scope.offers.save(offer);
    }
  });

}).call(this);
