// Generated by CoffeeScript 2.6.0
(function () {
  'use strict';
  angular.module('vs-lettings').config(function ($stateProvider) {
    $stateProvider.state('lettings_offers-list', {
      url: '/lettings/offers',
      template: require("./offers-list.html").default,
      controller: 'lettingsOffersListCtrl',
      data: {
        title: 'Vitalspace Lettings - Pending Offers',
        auth: ['lettings:agency', 'lettings:admin', 'lettings:superadmin']
      },
      resolve: {
        user: function (Auth) {
          return Auth.getPromise(['lettings:agency', 'lettings:admin', 'lettings:superadmin']);
        }
      }
    });
    $stateProvider.state('lettings_offers-list_historic', {
      url: '/lettings/offers/historic',
      template: require("./offers-list.html").default,
      controller: 'lettingsOffersListCtrl',
      data: {
        title: 'Vitalspace Lettings - Pending Offers',
        auth: ['lettings:agency', 'lettings:admin', 'lettings:superadmin'],
        data: {
          isHistoric: true
        }
      },
      resolve: {
        user: function (Auth) {
          return Auth.getPromise(['lettings:agency', 'lettings:admin', 'lettings:superadmin']);
        }
      }
    });
  });

}).call(this);
